Repository vinit105/ideaVault, pull requests merged in 2025-08, with the labels that each got.

#3 Added visibility for icons and pagination
  frontend/src/pages/Home.tsx
  frontend/src/pages/Ideas.tsx
Labels: gssoc25, level-1

#8 Fix the hover of submit your idea button
  frontend/src/pages/Home.tsx
Labels: gssoc25, level-1

#11 create workflow to check build errors
  .github/workflows/build-check.yml
Labels: gssoc25, level-2

#20 The browse ideas button is now working
  frontend/src/pages/Home.tsx
Labels: gssoc25, level-1

#21 The about page is now aligned and better UI
  frontend/src/pages/About.tsx
Labels: gssoc25, level-1

#24 Redesigned Footer, About Page, and Homepage UI for a Consistent and Engaging Experience – Closes #16
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Header.tsx
  frontend/src/index.css
  frontend/src/pages/About.tsx
  frontend/src/pages/Home.tsx
  package-lock.json
Labels: enhancement, gssoc25, level-1

#27 Updated the broken links in README.md
  README.md
Labels: documentation, gssoc25, level-1

#33 Convert Footer component from JSX to TSX
  frontend/src/components/Footer.tsx
Labels: enhancement, gssoc25, level-1

#36 feat: add legal pages and update routing in App component ISSUE 34
  frontend/src/App.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/pages/Ideas.tsx
  frontend/src/pages/License.tsx
  frontend/src/pages/Privacy.tsx
  frontend/src/pages/Terms.tsx
Labels: gssoc25, level-1

#38 feat: implement user authentication with JWT and cookie management ISSUE #18
  backend/package.json
  backend/src/middleware/auth.ts
  backend/src/models/User.ts
  backend/src/routes/auth.ts
  backend/src/server.ts
  package-lock.json
Labels: gssoc25, level-2, backend

#40 feat: implement authentication context and user management with login, registration, and protected routes #19 issue
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/hooks/useAuthGuard.tsx
  frontend/src/pages/Dashboard.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Register.tsx
  package-lock.json
  package.json
Labels: gssoc25, level-2, feature
